### ISSUE TITLE
Lag in the Confetti explosion

### ISSUE THREAD

**Issue by panmona** [daniel-lundin/react-dom-confetti#13]
I use this in an application of mine and we noticed quite a bit of lag in the confetti explosion. See the gif I attached:
![2018-04-25 18 09 05](https://user-images.githubusercontent.com/16801528/39258355-1eb8667c-48b4-11e8-8156-d7b2ff9444b2.gif)

I hope that you can resolve this issue.

**Comment by daniel-lundin** [comment]
It's hard to tell from a gif, but how are the other animations implemented?
This library only animates transform an opacity so it should be quite performant, but if the other animations trigger layouts it will probably interfere with the explosion.
Can you post a minimal reproducible codepen or similar?

**Comment by panmona** [comment]
@daniel-lundin I'll look into it.

**Comment by panmona** [comment]
Won't have time for that in the next time, I'll close this for now.

**Comment by panmona** [comment]
Maybe instead of using dom elements you could use CSS Houdini. Think this will speed things up a lot
