### ISSUE TITLE
Config particle colors

### ISSUE THREAD

**Issue by Tscheffrey** [daniel-lundin/react-dom-confetti#14]
dom-confetti sets the colors of the particles:
https://github.com/daniel-lundin/dom-confetti/blob/7c56b9ba4be7b7aae0766f5ccb58b58885bb0273/src/main.js#L1

Would be great if there was a way to control this in React.

**Comment by daniel-lundin** [comment]
Hi,

react-dom-confetti just passes the config prop to dom-confetti so if you pass a property `color` in the config object it should work as expected.
