### ISSUE TITLE
Please help me insert this into my WIX site

### ISSUE THREAD

**Issue by kirstendear** [daniel-lundin/react-dom-confetti#15]
Can someone please help me convert this into an HTML element suitable for my WIX site?

I like these settings.....i just have no idea what else to add to it to make it work.

import Confetti from 'react-dom-confetti';

const config = {
  angle: 51,
  spread: 360,
  startVelocity: 68,
  elementCount: 200,
  decay: 0.87
};
return <Confetti active={ someProp } config={ config }/>

****I have no idea what I need to add before and after this coding to make it compatible on my WIX site.

Please help me, someone.

I would also love this to be automatic when a certain page loads but I know that might be asking a bit much haha.

Thank you,

Kirsten

**Comment by panmona** [comment]
You first have to find a way to:
- get a standalone react component running in wix. Maybe something like [this](https://medium.com/@to_pe/how-to-add-react-to-a-simple-html-file-a11511c0235f) will work.

**Comment by daniel-lundin** [comment]
If it's not a React project you could use the underlying library instead:
[https://github.com/daniel-lundin/dom-confetti](dom-confetti)
