### ISSUE TITLE
v0.1.3 has wrong width and height types

### ISSUE THREAD

**Issue by FlopieUtd** [daniel-lundin/react-dom-confetti#27]
The width and height props used to be strings (i.e. "20px"), which worked just fine ( besides, on https://daniel-lundin.github.io/react-dom-confetti/ the width and height props are still provided as strings ).
Since version 0.1.3., type definitions for height and width were added as numbers. 
However, when I change "20px" to 20, the confetti no longer renders. Either the type definitions should be changed to either a number or string, or the confetti should still render when providing a number.

**Comment by AntonHanni** [comment]
I have the same issue. Changed height and width types to string in index.d.ts and worked fine afterwards.

**Comment by simon-holm** [comment]
I made a PR for it 2 weeks ago. Not sure how to get it merged

**Comment by lukeschunk** [comment]
this might be obvious but in the meantime i locked my version to `0.1.2` and kept width and height as strings to allow for confetti rendering 🎉

**Comment by daniel-lundin** [comment]
0.1.4 is now released which should fix this.
