### ISSUE TITLE
width and height not working (typescript)

### ISSUE THREAD

**Issue by codingyourlife** [daniel-lundin/react-dom-confetti#29]
The example shows width and height as string:
[https://daniel-lundin.github.io/react-dom-confetti/](https://daniel-lundin.github.io/react-dom-confetti/)

But node_modules/react-dom-confetti/index.d.ts shows:
```
interface ConfettiConfig {
    angle?: number;
    spread?: number;
    width?: number; //number not string
    height?: number; //number not string
    duration?: number;
    dragFriction?: number;
    stagger?: number;
    startVelocity?: number;
    elementCount?: number;
    decay?: number;
    colors?: string[];
    random?: () => number;
}
```
width and height as number or empty. It also doesn't work when I pass in:
```
const confettiConfig: ConfettiConfig = {
    angle,
    width: 20,
    height: 20
}
```

**Comment by sepehr500** [comment]
I have the same issue

**Comment by Nautman** [comment]
I also have this issue. Does @daniel-lundin need help with a pull request?

**Comment by daniel-lundin** [comment]
I just merged a PR with a fix for the typescript definition. Will do release later today. Thanks for the patience

**Comment by Nautman** [comment]
Great thanks, @daniel-lundin! Much appreciated for the hasty work :)

**Comment by daniel-lundin** [comment]
0.1.4 is now released which should fix this.
