### ISSUE TITLE
SCRIPT5045: Assignment to read-only properties is not allowed in strict mode

### ISSUE THREAD

**Issue by wojtekmaj** [daniel-lundin/react-dom-confetti#7]
Hi!
On Microsoft Edge, this is the error I'm getting ~1 second after clicking the button.
Confetti never comes. :(

**Comment by daniel-lundin** [comment]
That's too bad :(
Do you get any stack trace telling you where it happens?
I don't have access to Edge a.t.m..

**Comment by wojtekmaj** [comment]
You apparently can't just apply new classList like that:

![image](https://user-images.githubusercontent.com/5426427/31058213-4898586e-a6f0-11e7-8855-a76d3e3d951f.png)

I guess you should use classList.add('fetti') for that. But whatever your transpiler does, breaks it up.

Stack is minified so there's not much of a use... :(

**Comment by wojtekmaj** [comment]
Actually, you have fixed it already, only your demo page still is not updated.

https://github.com/daniel-lundin/dom-confetti/commit/f0ca578d012d26034d3154268851ad7ee4a9eb35#diff-1c90ff38a08209f9ebd4d05d1e43358eL14

**Comment by daniel-lundin** [comment]
Ahh, yes I remember something about removing an unnecessary class. I will update the demo page, thanks for noticing!

**Comment by wojtekmaj** [comment]
FYI it's working like a charm, no more Edge-specific issues :)

**Comment by daniel-lundin** [comment]
Great, thanks fot acknowledging!
